### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by cis-computer** [akuehlewind/ESPHome-touch-display-mount#2]
Hallo Adrian
ich wollte gerade Deinen Code ausprobieren, bekomme aber folgenen Fehler. Was mache ich falsch?

`INFO ESPHome 2024.11.3
INFO Reading configuration /config/esphome/test.yaml...
INFO Detected timezone 'Europe/Berlin'
ERROR Unexpected exception while reading configuration:
Traceback (most recent call last):
  File "/usr/local/bin/esphome", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/esphome/esphome/__main__.py", line 1036, in main
    return run_esphome(sys.argv)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/__main__.py", line 1014, in run_esphome
    config = read_config(dict(args.substitution) if args.substitution else {})
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/config.py", line 1091, in read_config
    res = load_config(command_line_substitutions)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/config.py", line 945, in load_config
    return _load_config(command_line_substitutions)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/config.py", line 935, in _load_config
    return validate_config(config, command_line_substitutions)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/config.py", line 859, in validate_config
    result.run_validation_steps()
  File "/esphome/esphome/config.py", line 142, in run_validation_steps
    task.step.run(self)
  File "/esphome/esphome/config.py", line 562, in run
    validated = schema(self.conf)
                ^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/voluptuous_schema.py", line 35, in __call__
    res = super().__call__(data)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/voluptuous/schema_builder.py", line 281, in __call__
    return self._compiled([], data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/voluptuous/validators.py", line 251, in _run
    return self._exec(self._compiled, value, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/voluptuous/validators.py", line 379, in _exec
    v = func(path, v)
        ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/voluptuous/schema_builder.py", line 855, in validate_callable
    return schema(data)
           ^^^^^^^^^^^^
  File "/esphome/esphome/components/font/__init__.py", line 159, in validate_glyphs
    check_missing_glyphs(fileconf[CONF_PATH], glyphspoints)
  File "/esphome/esphome/components/font/__init__.py", line 99, in check_missing_glyphs
    font = FONT_CACHE[file]
           ~~~~~~~~~~^^^^^^
  File "/esphome/esphome/components/font/__init__.py", line 56, in __missing__
    res = self[key] = freetype.Face(key)
                      ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/freetype/__init__.py", line 1192, in __init__
    raise FT_Exception(error)
freetype.ft_errors.FT_Exception: FT_Exception:  (unknown file format)`

**Comment by cis-computer** [comment]
Ne, den Fehler hab ich natürlich zuerst gemacht ;-( - gab aber ne eindeutige (andere) Fehlermeldung

**Comment by akuehlewind** [comment]
Kannst versuchen deinen Fonts Cache in Esphome zu löschen, ESPhome neuzustarten oder die verwendeten Schriftarten durch eine andere zu ersetzen 🤷‍♂️
